name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python FirstProgram_test.py
      id: python-firstprogram_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Python MadLib_test.py
      id: python-madlib_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-FIRSTPROGRAM_TEST-PY_RESULTS: "${{steps.python-firstprogram_test-py.outputs.result}}"
        PYTHON-MADLIB_TEST-PY_RESULTS: "${{steps.python-madlib_test-py.outputs.result}}"
      with:
        runners: python-firstprogram_test-py,python-madlib_test-py
